create database c1020g1;
use c1020g1;
create table student(id int, name varchar(100), address varchar(100));
select id from student;
insert into student value (1, 'Le Doan Tung', 'Hai Duong');
use c1020g1;
create table classes (id int, name varchar(10), language nvarchar(50), description nvarchar(250));
alter table classes modify language nvarchar(20);
alter table classes modify language nvarchar(20) not null;
alter table classes add constraint khoachinh PRIMARY KEY (id);
alter table student add constraint khoachinh2 primary key (id);
alter table student add column class_id int;
alter table student add constraint khoangoai1 foreign key (class_id) references classes(id);
select * from student where id=1;
select * from student where name='Vu Thi Kieu Anh';
update student set name='Vu Kieu Anh' where name = 'Vu Thi Kieu Anh';
update student set name= 'Vu Minh Trang' where id= 5;
select s.name as tenHV, c.name as 'tenlop' from student s join classes c on s.class_id = c.id;
select student.name, classes.name from student join classes on student.class_id = classes.id;
insert into classes value (6, 'C1120G1', 'Java', 'Java Full time');
select * from classes where description = 'Java Full time';
update classes set language = 'Java', description = 'Java Part time' where id=5;
select name from classes where description like '%Java';
select * from classes where description = '%Java%';
delete from classes where name='Demo';
alter table student add column point int;
select name, point, address from student where student.point between 6 and 9 and name like '%Kieu Anh%';
select * from student join classes where student.class_id = classes.id;
select * from student left join classes c on student.class_id = c.id;
select * from student;
select AVG(point) as  DTB from student;
select SUM(point) as  DTB from student;
select MAX(point) as  DTB from student;
select MIN(point) as  DTB from student;
select UCASE(name) from student;
select * from student order by point DESC , id DESC ;